name: Scheduler
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get versions
        run: |
          echo LATEST_VERSION=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name') >> $GITHUB_ENV
          echo CURRENT_VERSION=\
            $(\
              curl \
                -s https://api.github.com/users/SamuNatsu/packages/container/mihomo-docker/versions \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              | \
              jq \
                -r '\
                  map(\
                    select(\
                      ((.metadata.container.tags | length) > 0)\
                      and\
                      (.metadata.container.tags | map(test("^sha256-") | not) | all)\
                    )\
                  )\
                  |\
                  .[0].metadata.container.tags[0]'\
            ) >> $GITHUB_ENV
      - name: Print version
        run: echo $CURRENT_VERSION
